{% set version = "1.0.0" %}

package:
  name: cymbal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cymbal/cymbal-{{ version }}.tar.gz
  sha256: 1c79a00190bc8646505392b904e6e76410e98018f96f247ff7d363365241e2e0
  patches:
    - 0000-exclude-tests-package.patch

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - python-clang

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - cymbal
  commands:
    - pip check
    - coverage run --source=cymbal --branch -m pytest -vv --tb=long --color=yes -k "not class_template_args"
    - coverage report --show-missing --skip-covered --fail-under=64

about:
  home: http://github.com/AndrewWalker/cymbal
  summary: Helps you add functionality missing from libclang Python bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
