{% set version = "1.0.0" %}

package:
  name: cymbal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cymbal/cymbal-{{ version }}.tar.gz
  sha256: 1c79a00190bc8646505392b904e6e76410e98018f96f247ff7d363365241e2e0
  patches:
    - 0000-exclude-tests-package.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - python-clang

test:
  source_files:
    - tests
  imports:
    - cymbal
  commands:
    - pip check
    - pytest -vv -k "not class_template_args" --cov cymbal --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 65
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: http://github.com/AndrewWalker/cymbal
  summary: Helps you add functionality missing from libclang Python bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
